### ISSUE TITLE
Unable to run and debug locally with Visual Studio Code

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/app-templates-java-openai-springapps#34]
Unable to run and debug locally with Visual Studio Code
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run and Debug Locally.

### Any log messages given by the failure
>N

### Expected/desired behavior
>We cannot run and debug locally using Visual Studio Code according to the Readme, because the `.vscode` folder in this template lacks the `launch.json` and `tasks.json` files.

### Versions
>1.0.0

**Comment by pmalarme** [comment]
Thank you for your proposition. To be evaluated, can you please follow the template for the issues of this repository. For the task, we would need more details about the tasks that are required for debugging that are not available in npm scripts and java projects. Thank you!

**Comment by pmalarme** [comment]
- Instructions to run and build the frontend: https://github.com/Azure-Samples/app-templates-java-openai-springapps/blob/main/src/frontend/README.MD
- Instructions to run and build the AI Shopping Cart Service: https://github.com/Azure-Samples/app-templates-java-openai-springapps/blob/main/src/ai-shopping-cart-service/README.md

**Comment by NanaXiong00** [comment]
> Thank you for your proposition. To be evaluated, can you please follow the template for the issues of this repository. For the task, we would need more details about the tasks that are required for debugging that are not available in npm scripts and java projects. Thank you!

@pmalarme, If the tasks required for debugging are not available in npm scripts and java projects, we recommend removing `Run and Debug Locally` in `README.md`.
<img width="609" alt="image" src="https://github.com/Azure-Samples/app-templates-java-openai-springapps/assets/138103031/db8033df-e03b-43bf-84e1-0b97478d1927">

**Comment by pmalarme** [comment]
> > Thank you for your proposition. To be evaluated, can you please follow the template for the issues of this repository. For the task, we would need more details about the tasks that are required for debugging that are not available in npm scripts and java projects. Thank you!
> 
> @pmalarme, If the tasks required for debugging are not available in npm scripts and java projects, we recommend removing `Run and Debug Locally` in `README.md`. <img alt="image" width="609" src="https://user-images.githubusercontent.com/138103031/263607128-db8033df-e03b-43bf-84e1-0b97478d1927.png">

Thank you for your comment. I'm going to explore this. In the meantime can you update the description to follow the template and the guidelines of this repository.

**Comment by pmalarme** [comment]
Integrated in next release
